### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dumps'

### ISSUE THREAD

**Issue by mzjuin** [minimaxir/gpt-2-cloud-run#14]
Running fine in a docker, when i tried to run on my desktop error below came out.
`Traceback (most recent call last):
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "app.py", line 58, in homepage
    headers=response_header)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/responses.py", line 42, in __init__
    self.body = self.render(content)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/starlette/responses.py", line 159, in render
    return ujson.dumps(content, ensure_ascii=False).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'dumps'`

**Comment by mzjuin** [comment]
After some searches. I found that request.json() is clashing with some other lib.
bug: 
https://stackoverflow.com/questions/11369734/python-json-module-has-no-attribute-dumps

what I did to resolve this is I created another clean conda env for gpt-2-cloud-run to run, with only required packeges stated in the dockerfile. Now it can run on my local machine with gpu.
